### ISSUE TITLE
Drawing of Hidden Lines in 2D drawings

### ISSUE THREAD

**Issue by RyanMDev** [Microvellum/Fluid-Designer#27]
**Description:**
Need a way to represent hidden lines in a 2d drawing for shelves, roll outs, etc. that are hidden by a cabinet door. 

![hidden_shelf_lines](https://cloud.githubusercontent.com/assets/6529544/24920982/26197e4c-1e9e-11e7-91b9-d1bfa46c219c.png)

**Tasks:**
- [x] Modify 2d drawing code to create new lineset for hidden lines.
- [x] Create and initialize line sets and line styles outside of 'add camera' function.
- [x] Set correct line set and line style parameters for detecting hidden lines
- [x] Draw hidden lines as dashed lines.
- [x] Update relevant assemblies to implement drawing of hidden lines.

**Comment by RyanMDev** [comment]
Allow additional rendering options. Render dimensions in cycles renders.
